builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE
      - config.toml

dockers:
  - goos: linux
    goarch: amd64
    ids:
    - cic-keep-alive
    image_templates:
    - "ghcr.io/grassrootseconomics/cic-keep-alive/cic-keep-alive:latest"
    - "ghcr.io/grassrootseconomics/cic-keep-alive/cic-keep-alive:{{ .Tag }}"
    dockerfile: Dockerfile
    extra_files:
    - config.toml
    - LICENSE
